Repository shelljs/shx, pull requests merged in 2025-03, with the labels that each got.

#228 chore: update shelljs and drop old node support
  .github/workflows/main.yml
  README.md
  package.json
  scripts/check-node-support.js
  src/shx.js
  test/specs/cli.js
Labels: chore, breaking

#229 chore: drop non-LTS node versions
  .github/workflows/main.yml
  README.md
  scripts/check-node-support.js
Labels: chore, breaking

#230 chore: drop some dependencies and simplify
  .github/workflows/main.yml
  package.json
Labels: chore

#231 chore: update dependencies
  .eslintrc.json
  .mocharc.js
  package.json
  test/mocha.opts
Labels: chore

#232 fix: add back ShellJS version in --version
  .gitignore
  package-lock.json
  package.json
  src/shx.js
  test/specs/cli.js
Labels: fix

#189 Adding a global --negate flag
  README.md
  src/help.js
  src/shx.js
  test/specs/cli.js
Labels: feat
